### ISSUE TITLE
[ENHANCEMENT] Patch items

### ISSUE THREAD

**Issue by tomhamer** [marqo-ai/marqo#100]
**Is your feature request related to a problem? Please describe.**
We should be able to update a single field (for example some metadata) without having to reindex all the document data.

**Describe the solution you'd like**
We should have a patch operation for documents where if the user provides just some of the fields, those fields are added/updated as per the provided ID.

**Describe alternatives you've considered**
We could just rely on updates, but for some use cases users need to be able to update like 10k embeddings and only need to change a metadata field, so doing all the transformations is a big waste of compute

**Additional context**

**Comment by jn2clark** [comment]
Completed in https://github.com/marqo-ai/marqo/pull/117.
