### ISSUE TITLE
[BUG] UnicodeDecodeError while reading simplewiki.json

### ISSUE THREAD

**Issue by anubhavlohani** [marqo-ai/marqo#102]
**Describe the bug**
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 34260: character maps to <undefined>
Python's `json` is unable to read simplewiki dataset.
Python Version: 3.9.13

**Console Output**
<pre>
(venv) D:\Codes\marqo-wiki\src>python simple_wiki_demo.py
Traceback (most recent call last):
&emsp;File "D:\Codes\marqo-wiki\src\simple_wiki_demo.py", line 34, in <module>
&emsp;&emsp;data = read_json(dataset_file)
&emsp;File "D:\Codes\marqo-wiki\src\simple_wiki_demo.py", line 15, in read_json
&emsp;&emsp;data = json.load(f)
&emsp;File "C:\Users\anubh\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
&emsp;&emsp;return loads(fp.read(),
&emsp;File "C:\Users\anubh\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
&emsp;&emsp;return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 34260: character maps to < undefined >
</pre>

**To Reproduce**
1. Go to [simplewiki example](https://github.com/marqo-ai/marqo/tree/mainline/examples/SimpleWiki)
2. Run `simple_wiki_demo.py` using `python simple_wiki_demo.py`
3. See error

**Expected behavior**
`json.load` is supposed to load the data without any errors.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home

**Additional context**
Working fix: change encoding type while reading file in `read_json` function. Replace line 13 of [this demo script](https://github.com/marqo-ai/marqo/blob/mainline/examples/SimpleWiki/simple_wiki_demo.py) --> `with open(filename, 'r', encoding='utf-8') as f:`

**Comment by anubhavlohani** [comment]
If this bug is reproducible, I'd like to fix it please.

**Comment by jn2clark** [comment]
Hi @anubhavlohani , a couple of questions i) would you be able to paste the full console output of the error, ii) as well as your python version and iii) if you found a fix could you paste that as well? I am trying to reproduce the error now. Thanks

**Comment by anubhavlohani** [comment]
> Hi @anubhavlohani , a couple of questions i) would you be able to paste the full console output of the error, ii) as well as your python version and iii) if you found a fix could you paste that as well? I am trying to reproduce the error now. Thanks

Hi @jn2clark, I've updated the original commented with the requested details.

**Comment by jn2clark** [comment]
Thanks. I just merged a PR to update the script https://github.com/marqo-ai/marqo/pull/104 and https://github.com/marqo-ai/marqo/blob/mainline/examples/SimpleWiki/simple_wiki_demo.py#L13

**Comment by anubhavlohani** [comment]
> Thanks. I just merged a PR to update the script #104 and https://github.com/marqo-ai/marqo/blob/mainline/examples/SimpleWiki/simple_wiki_demo.py#L13

Great. Glad I could help out 🙂
