### ISSUE TITLE
[BUG] not receiving the desired results

### ISSUE THREAD

**Issue by rajshahdev** [marqo-ai/marqo#107]
**Describe the bug**
i took the code from readme and i change the first dict inside the list
```
    {
        "Title": "Indian culture",
        "Description": '''What, one wonders, is the lowest common denominator of Indian culture today? The attractive Hema Malini? The songs of Vinidh Barati? The attractive Hema Malini? The sons of Vinidh Barati?
 Or the mouth-watering Masala Dosa? Delectable as these may be, each yield pride of place to that false (?) symbol of a new era-the synthetic fibre. In less than twenty years the nylon sari and the terylene shirt have swept the countryside, penetrated to the farthest corners of the land and persuaded every common man, woman and child that the key to success in the present-day world lie in artificial fibers: glass nylon, crepe nylon, tery mixes, polyesters and what have you. More than the bicycles, the wristwatch or the transistor radio, synthetic clothes have come to represent the first step away form the village square. The village lass treasures the flashy nylon sari in her trousseau most delay; the village youth gets a great kick out of his cheap terrycot shirt and trousers, the nearest he can approximate to the expensive synthetic sported by his wealthy citybred contemporaries. And the Neo-rich craze for ‘phoren’ is nowhere more apparent than in the price that people will pay for smuggled, stolen, begged borrowed second hand or thrown away synthetics. Alas, even the uniformity of nylon. 

'''
    }
```

and the question i ask is to :- `q="The latest symbol of modernity for the rural people is?"`

now when i redo the question that is now i have the same questions as in the readme doc and run using python command but i still get the output of previous question.

the expected output is the same in readme!

the system is mac m1 and i am running with the help of docker.

**Comment by jn2clark** [comment]
Hi @rajshahdev , would you be able to post the full code you used?

**Comment by rajshahdev** [comment]
yep sure!

**Comment by rajshahdev** [comment]
here,
https://codefile.io/f/ve161e8ViIiO7KdHrcpV
after this i just ran the file and redo all the changes as same as in our readme file https://codefile.io/f/3Z0nX9wf8DZUlpTMkUwS but i got the output of previous one.

**Comment by jn2clark** [comment]
thanks @rajshahdev . I think I know what is maybe happening. if i run those snippets i get the same result for the two queries. if you change the query to 
```
results = mq.index("my-first-index").search(
         q="What do astronauts wear to work on the moon?"
  )
```
then it gives the 'correct' result. could you paste the full code together as it was run (in the same order) and the outputs?
