### ISSUE TITLE
Tensor prefiltering not working for fields with spaces [BUG]

### ISSUE THREAD

**Issue by pandu-k** [marqo-ai/marqo#115]
**Describe the bug**
Tensor prefiltering not working for fields with spaces. When a filter is applied to a field with a space, no documents are retrieved.

**To Reproduce**
1. Have Marqo running 
2. Index some documents. One should have a field with a space in it:
```
curl -XPOST  'http://localhost:8882/indexes/my-irst-ix/documents?refresh=true&device=cpu' -H 'Content-type:application/json' -d '
[ 
    {
        "Title": "Honey is a delectable food stuff", 
        "Desc" : "some boring description",
        "_id": "honey_facts_119",
        "gapped field": "wololo"
    }, {
        "Title": "Space exploration",
        "Desc": "mooooon! Space!!!!",
        "_id": "moon_fact_145"
    }
]'
```
Doing a filtered lexical search works (document  id: "honey_facts_119" is retrieved):
```
curl -XPOST  'http://localhost:8882/indexes/my-irst-ix/search?device=cpu' -H 'Content-type:application/json' -d '{
    "q": "what do bears eat?",
    "searchMethod": "LEXICAL",
    "filter": "gapped\\ field:wololo"
}'
```
But doing a filtered tensor search doesn't (document  id: "honey_facts_119" isn't retrieved):
```
curl -XPOST  'http://localhost:8882/indexes/my-irst-ix/search?device=cpu' -H 'Content-type:application/json' -d '{
    "q": "what do bears eat?",
    "searchMethod": "TENSOR",
    "filter": "gapped\\ field:wololo"
}'
```

**Expected behavior**
When a filter is applied to a field with a space, the documents should be retrieved, in the same way it is for lexical search

**Desktop (please complete the following information):**
 - OS: Ubuntu amd64 
 - Version 0.0.3

**Additional context**

**Comment by PawanPatil19** [comment]
Can you assign this issue to me?

**Comment by pandu-k** [comment]
Looking at this issue, I think it's a problem with Marqo-os kNN filtering having trouble parsing fields with spaces, or at least with escaping the space with a backslash.

What solution are you thinking of @PawanPatil19 ?

**Comment by pandu-k** [comment]
Resolved by https://github.com/marqo-ai/marqo/pull/213
