### ISSUE TITLE
[BUG] Getting started curl documentation is outdated/wrong

### ISSUE THREAD

**Issue by danyilq** [marqo-ai/marqo#129]
Curl getting started says that we use `/indices` api, while package itself uses `/indexes`.  
Also execution of the getting started commands return wrong response  `{"detail":"Not Found"}{"detail":"Not Found"}`.  
It's especially confusing when switching from package to curl and vice versa.

<img width="973" alt="image" src="https://user-images.githubusercontent.com/107251367/196521128-1fb279e7-a95a-4bf2-9984-2d2ce8282c39.png">

**Comment by pandu-k** [comment]
Thanks for spotting that, @danyilq - Fixed!
