### ISSUE TITLE
[ENHANCEMENT] - Get Indices

### ISSUE THREAD

**Issue by kdewald** [marqo-ai/marqo#130]
**Is your feature request related to a problem? Please describe.**
I have no way of querying which indices have been loaded to OpenSearch to perform operations on them.

**Describe the solution you'd like**
A function on the `Client` object to return a list of indices.

**Comment by kdewald** [comment]
Also, I think something similar should apply to documents. There's no way of knowing the full list of document ids.

**Comment by jn2clark** [comment]
merged in https://github.com/marqo-ai/py-marqo/pull/36
