### ISSUE TITLE
[BUG] Image to Image search results are not correct

### ISSUE THREAD

**Issue by wanliAlex** [marqo-ai/marqo#207]
**Describe the bug**

When I try to search for similar images using an image that is already in the index, I expect the first returned result should be the provided image. However, in some circumstances, the searched image can not be found even in the top 500 results.

**Comment by pandu-k** [comment]
Hi @wanliAlex are you able to attach example code that can reproduce this error?

**Comment by jn2clark** [comment]
@wanliAlex do you have a code snippet to reproduce?

**Comment by wanliAlex** [comment]
The problem is noticed when I try to test the inference on a larger dataset.

Dataset: coco train 2014 [link](https://cocodataset.org/#download)

Dataset size: 50k

The code to index the dataset:

```python
MODEL = "ViT-L/14"

settings = {
        "model": MODEL,
        "treat_urls_and_pointers_as_images": True,
        }

client.index(index_name).add_documents(documents, device="cuda", processes=4, client_batch_size= 50)
```

I randomly select 4 images to do an image-to-image search, which are:

![image](https://user-images.githubusercontent.com/49334982/206935852-c9237724-8a71-4870-aa26-7faed8c52e01.png)


The code to do the search:

```python
search_results = client.index(index_name).search(docker_path + img_name, 
                        searchable_attributes=['image_docker'], limit = 10,
                        device='cuda')
```

The total code to plot the results:

```python
for search_label, img_name in zip(image_search_labels, imgs_name):
    search_results = client.index(index_name).search(docker_path + img_name, 
                        searchable_attributes=['image_docker'], limit = 10,
                        device='cuda')
    score = 0
    fig, axes = plt.subplots(nrows = 2, ncols = 5, figsize=(15,8))

    for i, result in enumerate(search_results["hits"]):
        img_name = result["image_docker"]
        local_path_img_name = img_name.replace(docker_path, images_directory)
        img = Image.open(local_path_img_name)
        axes[i//5,i%5].imshow(img)
    plt.show()    
    for result in search_results["hits"]:
        img_id = int(result["_id"][-10:-4])
        anns = coco.loadAnns(coco.getAnnIds(imgIds = img_id))
        result_cat = []
        for an in anns:
            cat = coco.loadCats(an["category_id"])[0]
            result_cat.append(cat['name'])
        
        score += 10 * len(set(search_label) & set(result_cat)) / len(search_label)
        
    print(f"The score for searching \"{search_label}\" is {round(score)} %.")
```

The results are shown as below:

1) Image 1:

![image](https://user-images.githubusercontent.com/49334982/206935906-7dc8cb5e-3441-4eb9-a977-bff81a98e183.png)
2) Image 2:

![image](https://user-images.githubusercontent.com/49334982/206935924-b29d7a92-7b05-4ed3-892c-9c5e06550d17.png)

3) Image 3:

![image](https://user-images.githubusercontent.com/49334982/206935931-758fda80-d332-4179-a6fb-eb3146753151.png)

4) Image 4:

![image](https://user-images.githubusercontent.com/49334982/206935940-ac29ed42-4024-43d4-a9a3-81a18b590e70.png)

### Bug description:

I expect that the searched image should appear as the top hit in the returned results. However, except for image 3, we can’t find the searched images in the returned results.

I tried to increase the number of returned results to a larger size (50, 100) but still can the searched image. The image is somehow filtered out.

I can have the expected result (searched image as the top return) when the dataset is relatively small (5k).

**Comment by wanliAlex** [comment]
It is noticed that changing the value `m`  may resolve this issue.
