### ISSUE TITLE
[BUG] Simple Wikipedia Demo error - missing imports

### ISSUE THREAD

**Issue by georgewritescode** [marqo-ai/marqo#215]
**Describe the bug**
Missing imports in Simple Wikipedia Demo

errors:
`NameError: name 'math' is not defined` for numpy, math, copy
`TypeError: Index.add_documents() got an unexpected keyword argument 'batch_size'`

**To Reproduce**
- Run Marqo
- Run `` python3 simple_wiki_demo.py``

**Expected behavior**
Missing imports error

**Desktop (please complete the following information):**
 - OS: MacOS on M-series Macbook air (M2)
 - Marqo version: 0.0.8

**Additional context**
Will be submitting a PR shortly

**Comment by jn2clark** [comment]
Thanks @georgewritescode ! A PR would be great. This was my fault, I did not update the demo :(

**Comment by georgewritescode** [comment]
@jn2clark , no problem 👍
PR created [https://github.com/marqo-ai/marqo/pull/216](https://github.com/marqo-ai/marqo/pull/216)

**Comment by jn2clark** [comment]
closing for now. fixed in https://github.com/marqo-ai/marqo/pull/216
