### ISSUE TITLE
Unsupported Docker Images for M1 (arm64)

### ISSUE THREAD

**Issue by aryanagarwal9** [marqo-ai/marqo#24]
I have an M1 MacBook Pro running macOS Monterey v12.5. Crashing behaviour is being caused when I try to install Marqo through the following Docker commands:
- `docker rm -f marqo`
- `DOCKER_BUILDKIT=1 docker build . -t marqo_docker_0`
- `docker run --name marqo --privileged -p 8000:8000 --add-host host.docker.internal:host-gateway marqo_docker_0`

**Error messages:**
- `Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Starting supervisor
starting dockerd command
dockerd command complete
Waiting for processes to be running
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Process dockerd is not running yet. Retrying in 1 seconds`

- `failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.4 (legacy): can't initialize iptables table 'nat': iptables who? (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.`

The first error message originates from the `run_marqo.sh` file, and the second one is a docker error message.

**Comment by aryanagarwal9** [comment]
marqo uses images form `cruizba/ubuntu-dind` which does not support arm64, so that seems like the reason for the crashing behaviour.

I tried adding the `--platform linux/amd64` to the `docker run..` command. Though that removed the warning, the crashing behaviour was still there. Using arm64 supported source images to construct the docker should probably solve the issue.

There is a temporary fix for this problem - instead of using DIND, we can build & run the `marqo` docker container and connect to `marqo-os` which is running on the host.

**Steps:**

- Run the following command (directory doesn't matter): 
```bash
docker run --name marqo-os --platform linux/amd64 -id -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" marqoai/marqo-os:0.0.2
```
- On a new or different shell, `cd` into the cloned directory, and run the following command:
```bash
docker rm -f marqo &&
     DOCKER_BUILDKIT=1 docker build . -t marqo_docker_0 && 
     docker run --name marqo --privileged -p 8882:8882 --add-host host.docker.internal:host-gateway \
         -e "OPENSEARCH_URL=https://localhost:9200" marqo_docker_0
```

- To start using marqo, follow Getting Started, Step 3 in the README file.

**Comment by pandu-k** [comment]
Thanks Aryan. Your solution is great if users want to build and then run Marqo.

If users want to simply pull the Marqo image from docker and run it, I suggest this solution:

**Steps:**

- Run the following command, to start the Marqo-OpenSearch backend (directory doesn't matter). Note the `--platform linux/amd64` option: 
```bash
docker run --name marqo-os --platform linux/amd64 -id -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" marqoai/marqo-os:0.0.2
```
- Then, run the following command to run Marqo
```bash
docker rm -f marqo && 
     docker run --name marqo -p 8882:8882 --add-host host.docker.internal:host-gateway \
         -e "OPENSEARCH_URL=https://localhost:9200/" marqoai/marqo:0.0.3
```
