### ISSUE TITLE
[ENHANCEMENT] Model Cache Key Format

### ISSUE THREAD

**Issue by wanliAlex** [marqo-ai/marqo#240]
**Is your feature request related to a problem? Please describe.**
Our current `model_cache_key` stored in `available_models` is a string that is hard to split, eg:

"ViT-L/14ViT-L/14768clipcpu"

see [code](https://github.com/marqo-ai/marqo/blob/46e5005a6eeda11a571611cc8b42e03cc86ddf1f/src/marqo/s2_inference/s2_inference.py#L66) here

**Describe the solution you'd like**
add a splittable symbol between different parts:

"ViT-L/14,ViT-L/14,768,clip,cpu"

**Comment by wanliAlex** [comment]
# Easy Accessible Solution for Model Cache Key

`model_cache_key` is used as a key in s2_inference.py, `available_models` dictionary (see this [line](https://github.com/marqo-ai/marqo/blob/f1d15e9167c15791330d9cf15d9319da22b49abd/src/marqo/s2_inference/s2_inference.py#L66) )to provide access to the loaded models. Any operations on the model (e.g., getting information, ejecting a model) rely on `model_cache_key`.

Currently, the model cache key is a string with all the properties (e.g., model name, device, dimensions) merged together. A model cache looks like this:

`"ViT-L/14ViT-L/14768clipcpu”`

This is not readable to users and hard to reference as a key value. A proper design should consider readability, accessibility, and distinguishability. Providing too much information will make the key hard to reference. Making the key too simple will loss the necessary information that should be exposed. Each `model_cache_key` should be distinguishable from each others to provide easy access to the mapped models.

 

The `available_models` have the dictionary structure:

```python
available_models = {
	model_cache_key_1 : model_1,
	model_cache_key_2 : model_2,
	...
	model_cache_key_3 : model_3
}
```

### Solution 1

We change `model_cache_key` to a tuple with `model_name`, `device` as the first two elements followed by other properties. It will look like

`("ViT-L/14", "cpu", "ViT-L/14", "768", "clip")` 

**Pros:** This method provides the best readable information to the users.  

**Cons:** However, the problem is accessibility. The users need to provide the whole tuple to access this key and the mapped model. One possible solution is that we can use the first two elements to distinguish the `model_cache_key` . However, after discussing with Pandu, there is still a small chance that the two models have the same `model_name` and `device` but with different properties mapping to two different models.

### Solution 2

Adding a `unique_id` to **Solution 1** so we can identify and reference them by using the `unique_id` . For example, a model cache key should look like:

`("_id: 587", "ViT-L/14", "cpu", "ViT-L/14", "768", "clip")`

**Pros:** it has readability and makes user easy to access by using `“_id:586”` 

******Cons:****** I think this looks good to me.


### Solution 3

We can add a inner dictionary in `available_models`, so now we have:

```python

available_models = {
          "model_cache_key_1" : { "model_name": "test1",
                                                    "device" : "cuda",
                                                    "model" : model1},

          "model_cache_key_2 : { "model_name": "test2",
                                                    "device" : "cpu",
                                                    "model" : model2},
}
 ```

When we need to call a model, we just need to call `available_models[model_cache_key]["model"]`. 

Pros: This exposes all the information about a cached model and it is very easy to fetch the required information.

Cons: This does not solve the problem that the user needs to input the long `model_cache_key` to eject a model.





```

**Comment by wanliAlex** [comment]
@pandu-k @jn2clark @aryanagarwal9 can I have your opinions on this one?

**Comment by jn2clark** [comment]
Thanks @wanliAlex . A couple of points:
1) how is the `_id` generated?
2) how are the models accessed by `_id`?

**Comment by wanliAlex** [comment]
> 
1. For `_id` generation, there are two ways,
option1: have this `_id` as a pre-assigned property for each model.
option2: generate this `_id` every time a `model_cache_key` is generated.

2. We can identify the `model_cache_key` by this unique id.

But I agree we just use the tuple `(model_name, device) ` as `model_cache_key`.

Each model should be uniquely identified by its `model_name`.
