### ISSUE TITLE
Throttling [ENHANCEMENT]

### ISSUE THREAD

**Issue by pandu-k** [marqo-ai/marqo#268]
**Is your feature request related to a problem? Please describe.**
Marqo doesn't currently have a throttling mechanism. 

**Describe the solution you'd like**
We need to throttle requests to Marqo, to prevent resources being extinguished. Search and indexing should have independent throttling mechanism to ensure search remains available.  

**Describe alternatives you've considered**
Throttling as a layer in front of Marqo. The downside is that Marqo has no protection for itself in different environments.

**Comment by vicilliar** [comment]
Done. Solved with PR: https://github.com/marqo-ai/marqo/pull/304
