### ISSUE TITLE
[ENHANCEMENT] stop in "INFO:NLTK setup:downloading nltk data...."

### ISSUE THREAD

**Issue by achao2013** [marqo-ai/marqo#271]
when i run `docker run --name marqo -it --privileged -p 8882:8882 --add-host host.docker.internal:host-gateway marqoai/marqo:latest`, the progress stop in "INFO:NLTK setup:downloading nltk data...." for 2 days.

can you provide an post download method to skip this step when we excute "docker run..."?

**Comment by achao2013** [comment]
@pandu-k @wanliAlex

**Comment by wanliAlex** [comment]
Thank you for raising the issue. We will investigate on it and get back to you soon.

**Comment by jn2clark** [comment]
Hi @achao2013 , would you be able to provide the following:
1) The OS you are using
2) The marqo version
3) A screenshot of what the logs are producing
4) If you have tried to start marqo again

If I understand it correctly, it is not getting past the download step - is that correct?

**Comment by achao2013** [comment]
ubuntu 18.04, version 0.0.11, screenshot lost because i have downloaded it in a good network enviroment. "If I understand it correctly, it is not getting past the download step - is that correct?" -yes, i recommend to provide an post download method to skip download step
