### ISSUE TITLE
[BUG] can not get right document num when using cross modal search

### ISSUE THREAD

**Issue by achao2013** [marqo-ai/marqo#275]
**Describe the bug**
Multi modal and cross modal search failed , after add_documents for image url, 'mq.index(index_name).get_stats()' return "{'numberOfDocuments': 0}". I tried text search text , that's ok. I tried 'wget docker_path' and its success ensure that the image url is right.

**To Reproduce**

follow https://medium.com/@wanli19940222/how-to-implement-text-to-image-search-on-marqo-in-5-lines-of-code-448f75bed1da ,

use my images,

after `mq.index(index_name).add_documents(documents, device="cpu", processes=1, client_batch_size= 1)`,  excute  `mq.index(index_name).get_stats()`, it return "{'numberOfDocuments': 0}"

**Expected behavior**
return {'numberOfDocuments': 10}

**Screenshots**

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/5026576/212840541-d31cbe15-f239-4be6-8b7c-2b353a8ac7d3.png">

**Desktop (please complete the following information):**
 - OS:ubuntu 18.04
 - Browser 
 - Version 0.3

**Comment by achao2013** [comment]
@pandu-k @wanliAlex

**Comment by wanliAlex** [comment]
Hi, thank you for using Marqo. It seems that images are not added to you index. Can you provide the image document, which is the `image_docker` in the article? Make sure Marqo can access it.

**Comment by achao2013** [comment]
> Hi, thank you for using Marqo. It seems that images are not added to you index. Can you provide the image document, which is the `image_docker` in the article? Make sure Marqo can access it.

the documents are as follows：
[{'image_docker': 'http://host.docker.internal:8222/1667810239.387798223.png', '_id': 0}, {'image_docker': 'http://host.docker.internal:8222/1667810239.487797999.png', '_id': 1}, {'image_docker': 'http://host.docker.internal:8222/1667810239.587798287.png', '_id': 2}, {'image_docker': 'http://host.docker.internal:8222/1667810239.687798447.png', '_id': 3}, {'image_docker': 'http://host.docker.internal:8222/1667810239.787736830.png', '_id': 4}, {'image_docker': 'http://host.docker.internal:8222/1667810239.887736766.png', '_id': 5}, {'image_docker': 'http://host.docker.internal:8222/1667810239.987736542.png', '_id': 6}, {'image_docker': 'http://host.docker.internal:8222/1667810240.087736030.png', '_id': 7}, {'image_docker': 'http://host.docker.internal:8222/1667810240.187736062.png', '_id': 8}, {'image_docker': 'http://host.docker.internal:8222/1667810240.287736030.png', '_id': 9}]

I tried 'wget image_docker' in the docker and its success ensure that the image url is right.


@wanliAlex

**Comment by wanliAlex** [comment]
Thanks. The documents look good. Can you provide a full copy of your code here?

**Comment by achao2013** [comment]
> Thanks. The documents look good. Can you provide a full copy of your code here?

import marqo
import os
mq = marqo.Client(url='http://xx.xx.xx.xx:8882')
index_name = "image-search-guide"

settings = {
 "model": "ViT-L/14",
 "treat_urls_and_pointers_as_images": True,
 }

mq.create_index(index_name, **settings)
import subprocess
local_dir = "/mnt/xxxx/database/2022_11_07_16_33/demo_marqo/"
pid = subprocess.Popen(["python3", "-m", "http.server", "8222", "--directory", local_dir], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
import glob
import os


locators = glob.glob(local_dir + "*.png")

docker_path = "http://host.docker.internal:8222/"
image_docker = [docker_path + os.path.basename(f) for f in locators]
print(image_docker)
documents = [{"image_docker" : image, "_id" : idx} for idx, image in enumerate(image_docker)]
print('documents:',documents)
mq.index(index_name).add_documents(documents, device="cpu", processes=1, client_batch_size= 1)

results = mq.index(index_name).get_stats()
print(results)

@wanliAlex

**Comment by wanliAlex** [comment]
Hi, sorry for the wait. The problem is this line
`documents = [{"image_docker" : image, "_id" : idx} for idx, image in enumerate(image_docker)]`

Can you change to 

`documents = [{"image_docker" : image, "_id" : str(idx)} for idx, image in enumerate(image_docker)]`

 and test again?

**Comment by wanliAlex** [comment]
> 

We also recommend you to follow the example [here](https://github.com/marqo-ai/marqo/blob/mainline/examples/ImageSearchGuide/imagesearchguide.ipynb).

**Comment by achao2013** [comment]
> Hi, sorry for the wait. The problem is this line `documents = [{"image_docker" : image, "_id" : idx} for idx, image in enumerate(image_docker)]`
> 
> Can you change to
> 
> `documents = [{"image_docker" : image, "_id" : str(idx)} for idx, image in enumerate(image_docker)]`
> 
> and test again?

thanks, it works

**Comment by achao2013** [comment]
> > 
> 
> We also recommend you to follow the example [here](https://github.com/marqo-ai/marqo/blob/mainline/examples/ImageSearchGuide/imagesearchguide.ipynb).

ok
