### ISSUE TITLE
[BUG] Query String Syntax Errors

### ISSUE THREAD

**Issue by vicilliar** [marqo-ai/marqo#284]
**ISSUE**
Since lexical search now uses Query Strings (which have a strict, non-fault-tolerant syntax), using lexical search with any faulty syntax results in Marqo errors.

Examples of faulty syntax:
1. Unbalanced quotes or parentheses
2. Special symbols (+ : - etc) not used properly
3. Operators like AND, OR, NOT, being used improperly

**POSSIBLE SOLUTIONS**
1. Use Simple Query Strings instead
Pros:
- fault tolerant

Cons:
- some functionalities may be lost (field-specific search per term, boosting/ranking, but further tests need to be done)
- syntax is different from query string (+ instead of AND, | instead of OR, etc)

SOLUTIONS
take string from customer
escape anything that isn't a quotation (with backslash)
group terms
if user escapes a quote, treat the quote literally
if user escapes their own +
maybe just do match instead?

Requirements:
- Should never return a syntax error
- Needs exact match functionality

FUTURE:
- should and must for now.
- could have a lexical search DSL flag option

2. Adjust error messages from Marqo so user understands the problem

**Comment by pandu-k** [comment]
Edge cases: 
- `"` 
- `"""hello`  
- `""" python docstring appeared"""`   
- `""`
- `something "" something else`
- `""" python docstring appeared""" "quotes behaving normally"`
- `` what about backticks `? ``
- `\" escaped quotes\"  what happens here?`
Also using single quotes or a mix of quotes instead of double quotes for the above cases

**Comment by vicilliar** [comment]
Expected behavior: 

**Scenario: Interfering double quote (neither opening or closing)**
Input: 
`"ter"m1" term2`
Output:
required terms: `ter"m1`
optional terms: `term2`

**Scenario: Unbalanced double quotes**
Input: 
`"term1" "term2" "term3`
Output:
required terms: `term1, term2`
optional terms: `"term3`

**Scenario: Escaped quotes**
Input: 
`\"term1\" "term2"`
Output:
required terms: `term2`
optional terms: `"term1"`

**Scenario: Python Docstring (or even more stacked quotes)**
Input: 
`""" python docstring appeared""" "quotes behaving normally"`
Output:
required terms: `", quotes behaving normally`
optional terms: `python, docstring, appeared"""`

**Scenario: Empty string**
Input: 
`something "" something else`
Output:
required terms: `{EMPTY STRING}`
optional terms: `something, something, else`

**Comment by vicilliar** [comment]
Make tests on upper/lowercase terms. "term" query will not auto lowercase the search, but the index analyzer might. 

for example, you may index  "HELLO THERE" which would get rewritten as "hello there". searching for "HELLO THERE" may not work in this case.

**Comment by vicilliar** [comment]
Fixed here: https://github.com/marqo-ai/marqo/pull/288
