### ISSUE TITLE
Prevent unnecessary code from being containerised [ENHANCEMENT]

### ISSUE THREAD

**Issue by pandu-k** [marqo-ai/marqo#292]
**Is your feature request related to a problem? Please describe.**
Unnecessary code - including tests and example - are ending up in the resulting Docker container.

**Describe the solution you'd like**
Only specify required files to copy in Dockerfile. 

**Additional context**

**Comment by jalajk24** [comment]
Can I work on this issue? I am pretty new to this

**Comment by jn2clark** [comment]
hi @jalajk24 ! sounds good! we can help with any questions and code reviews as needed. @pandu-k is probably going to be the most help here so I will loop him in.

**Comment by jalajk24** [comment]
@pandu-k  can you tell me how should i proceed with this issue??

**Comment by pandu-k** [comment]
Hi @jalajk24 ! Thanks for offering to help. What's your plan for solving this problem?

**Comment by jalajk24** [comment]
@pandu-k  first thing that i am thinking of is that which are useful files and to be contained by docker must be find out so how to get that is my doubt can you suggest something??

**Comment by pandu-k** [comment]
Completed in https://github.com/marqo-ai/marqo/pull/448
