### ISSUE TITLE
[BUG] Error in the middle of indexing

### ISSUE THREAD

**Issue by paul-marqoai** [marqo-ai/marqo#298]
**Describe the bug**
Marqo displays a server-side related error in the middle of idexing

**To Reproduce**
1. Index data using `flax-sentence-embeddings/all_datasets_v4_mpnet-base` model
2. Run the index script

**Expected behavior**
The index should be successfully done.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/121985792/215958089-529baf79-9187-4f9c-b138-9290b65e6124.png)

**Comment by VitusAcabado** [comment]
Closing issue as issue is with Marqo cloud.
