### ISSUE TITLE
[BUG] Persistent 429 Too Many Requests when trying to upload data

### ISSUE THREAD

**Issue by feature-hope** [marqo-ai/marqo#358]
**Describe the bug**
I have a problem with uploading my data. When I try to push any data (especially images) I eventually get a 429 error after which the index to which I tried to upload consistently responds with 429's no matter how many time passed or how many data I'm trying to upload. It still responds to the searches well, but I am not able to upload to this index anymore.  

It may be the problem with my configuration and me missing something important in the docs, but it seems that I tried everything. It would be great to get help. Thank you in advance!

**To Reproduce**
1. Run marqo with default settings
2. Create client in python script like in example
3. Run `mq.index(INDEX).add_documents(IMAGES, client_batch_size=25, server_batch_size=25, device='cpu', auto_refresh=True)`
where INDEX is the name of index and IMAGES is the list of objects in the form `{'image': URL}`
4. Eventually get 
```python
marqo.errors.MarqoWebError: MarqoWebError: MarqoWebError Error message: {'message': 'Marqo-OS received too many requests! Please try reducing the frequency of add_documents and update_documents calls.', 'code': 'too_many_requests', 'type': 'invalid_request', 'link': None}
```
5. Try again step 3. and get what is in step 4. again

**Expected behavior**
After some time all images are uploaded. Or after getting 429 I would be able to retry and don't get new 429's consistently

**Desktop:**
 - OS: Ubuntu 20.04.5 LTS
 - Version of marqo: 0.0.14 
 - Run without GPU

**Additional context**
I tried to set different parameters like batch sizes and numbers of processes. It can help to upload more documents sometimes, but in any case it will stop somewhere.
I also looked in the [docs](https://docs.marqo.ai/0.0.14/Advanced-Usage/configuration/) on this and tried to set different parameters for concurrency, but it didn't help.
The configuration with both batch sizes being 25 is my best try which allows to upload something, but fails anyway.

**Comment by jn2clark** [comment]
Hi @i-moiseev ! What are the resources like on the machine you are running on (RAM and cpu)? This can happen if opensearch does not have enough resources.

**Comment by feature-hope** [comment]
Hello, @jn2clark
I have 16Gb of RAM - when marqo is running around 8-9 Gb are occupied
CPU is AMD Ryzen 5 3500 6-Core

**Comment by jn2clark** [comment]
Thanks. That should be fine. What about free disk space?

**Comment by feature-hope** [comment]
I have around 5 Gb free now. Should I free more space for it to work?

**Comment by jn2clark** [comment]
ah, yeah. I think opensearch will complain if it is that low (ultimately depends on the size of the drive though).

**Comment by feature-hope** [comment]
How can I know if it will complain? I tried to enable debug logging, but didn't found anything related there

**Comment by jn2clark** [comment]
By default marqo and marqo-os run in the same docker container. what you can do is run them separately and view the open-search logs coming from marqo-os. to do this:
1. run marqo-os
`docker run --name marqo-os -id -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" marqoai/marqo-os:0.0.3`
2. run marqo
`docker run --name marqo --privileged -p 8882:8882 --add-host host.docker.internal:host-gateway \
         -e "OPENSEARCH_URL=https://localhost:9200" marqo_docker_0`

You can see here for reference https://github.com/marqo-ai/marqo/tree/mainline/src/marqo. 
The other option is to exec into the running marqo container and view the logs.

**Comment by feature-hope** [comment]
Well, I guess the issue was in the disk space as you mentioned... I have 480 Gb total and only 5 free. Now when I freed more space (18Gb) it works properly (at least until now).
I'm also running in the separate setup you provided and saw messages about fraction of the disk space like this:
```
[2023-02-27T12:03:27,872][INFO ][o.o.c.r.a.DiskThresholdMonitor] [47819d4d8edc] low disk watermark [85%] exceeded on [EudlUQFuRR2QdkHODhuPlQ][47819d4d8edc][/usr/share/opensearch/data/nodes/0] free: 17.4gb[14.9%], replicas will not be assigned to this node
```
Now I understand the issue, thank you very much for quick response!
I think this kind of problem could also be added to the documentation for people like me wondering why they are receiving this error.

Can I close this issue now?

**Comment by jn2clark** [comment]
No worries! Yes, I can close it. We will add a section to the documentation about this.
