### ISSUE TITLE
[BUG] API tests check out wrong branch when using branch names with (slash)

### ISSUE THREAD

**Issue by vicilliar** [marqo-ai/marqo#366]
**Describe the bug**
When running a CI workflow (`local_os_CI`, `dind_os_CI`, etc), the `marqo-api-tests` repo is used. This repo tests on a version of marqo determined by the branch the CI was run on (for example: `joshua-feature`). The branch is passed [here](https://github.com/marqo-ai/marqo/blob/mainline/.github/workflows/local_os_CI.yml#L90) and the branch switch happens [here](https://github.com/marqo-ai/marqo-api-tests/blob/mainline/scripts/clone_marqo_repo.sh#L25).

If the marqo branch has a slash (eg `joshua/feature`), the branch value passed will only be `feature`, causing the branch switch to fail with the error:
```
py3-local_os run-test-pre: commands[0] | bash /actions-runner/_work/marqo/marqo/scripts/clone_marqo_repo.sh /actions-runner/_work/marqo/marqo feature
Cloning into 'marqo'...
fatal: invalid reference: feature
```

 Tests will be run on the wrong branch.

**Expected behavior**
Two solutions are possible:
1. Do not use branch names with a slash
2. Change how the current branch name is sent to marqo-api-tests (currently it is `export MQ_API_TEST_BRANCH="${GITHUB_REF##*/}"`

**Desktop (please complete the following information):**
 - github actions

**Comment by vicilliar** [comment]
In `MQ_API_TEST_BRANCH="${GITHUB_REF##*/}"`:
The syntax `##*/` is a substring removal expression in Bash that removes everything up to and including the last forward slash `/` in the string.

For example, if `GITHUB_REF` is `refs/heads/main`, then `GITHUB_REF##*/` will evaluate to `main`.

How do we adjust this so that if `GITHUB_REF` is `refs/heads/joshua/feature`, we obtain `joshua/feature`?

**Comment by vicilliar** [comment]
We have 3 cases for `GITHUB_REF` depending on what triggered the workflow CI:
branch: `refs/heads/<branch_name>`
PR: `refs/pull/<pr_number>/merge`
tag: `refs/tags/<tag_name>`

Currently, since we use git switch, this is only needed for branches. 
1. Simplest solution:
use `MQ_API_TEST_BRANCH="${GITHUB_REF#refs/heads/}"`. This will work for branches and get the full branch name `<branch_name>`, but will have no effect on the other 2 cases

2. Alternative:
use `MQ_API_TEST_BRANCH=$(echo "${GITHUB_REF}" | cut -d'/' -f3-)`. This will get everything past the first 2 `/` characters in `GITHUB_REF`. This means for the 3 cases:

branch: `<branch_name>`
PR: `<pr_number>/merge`
tag: `<tag_name>`

any thoughts on which to implement? @pandu-k @Jeadie

**Comment by pandu-k** [comment]
Number 2 looks good to me. I can't think of when we'll use PRs/ tags, but we may in the future. Thanks for exploring the options @vicilliar !

**Comment by vicilliar** [comment]
done. https://github.com/marqo-ai/marqo/pull/382/files
