### ISSUE TITLE
[ENHANCEMENT] add support for e5 models

### ISSUE THREAD

**Issue by jn2clark** [marqo-ai/marqo#380]
**Is your feature request related to a problem? Please describe.**
New SOTA embedding models have been released. We should add these to the model registry for users and make it so fine-tuned versions can be also used. https://arxiv.org/pdf/2212.03533.pdf 
https://huggingface.co/intfloat/e5-small

They seem to differ slightly from the sbert format so might need some minor adjustments for loading. 

**Describe the solution you'd like**
Add the e5-X class of models to Marqo (e5-large, e5-small)

**Comment by vicilliar** [comment]
implemented: https://github.com/marqo-ai/marqo/pull/419
