### ISSUE TITLE
Tensor is not a valid Search Method

### ISSUE THREAD

**Issue by kwakuOfosuAgyeman** [marqo-ai/marqo#39]
When using the example in the readme to help test I get an error stating that tensor is not a valid search method

**To Reproduce**

1. After setting up the docker requirements I created a file
2. Copied the data from the read me to use in the file
3. Run it in my terminal
4. See error in terminal

**Expected behavior**
I expected it to show a similar result like what was in

**Screenshots**
![bugReport](https://user-images.githubusercontent.com/112822461/188351387-70468cef-9912-4f39-acfb-ac4588fbb21a.png)

**Desktop **
 - OS: Windows 11
 - Chrome

**Comment by jn2clark** [comment]
Thanks @kwakuOfosuAgyeman . Would you be able to paste the commands you were trying to run as well?

**Comment by jn2clark** [comment]
I was able to reproduce the result (Macbook 2019 12.4) and after installing the latest Marqo (0.0.3) it disappeared. Would you be able to try and re-install using the latest version?
`docker run --name marqo --privileged -p 8882:8882 --add-host host.docker.internal:host-gateway marqoai/marqo:0.0.3`

**Comment by kwakuOfosuAgyeman** [comment]
Thank you very much it appears to be working appropriately now
