### ISSUE TITLE
[BUG] Weighted queires - dict not an accepted query type

### ISSUE THREAD

**Issue by ILidzhade** [marqo-ai/marqo#399]
**Describe the bug**
As mentioned in [this doc](https://docs.marqo.ai/0.0.16/API-Reference/search/): Marqo provides the option for a weighted query in the form of a `dict` input

**To Reproduce**
search using a dict
`result = mq.index("my-first-index").search({'adventure': 1.0, 'time': -2.0}, searchable_attributes=['Title'])`

```
MarqoWebError: MarqoWebError: MarqoWebError Error message: {"detail":[{"loc":["body","q"],"msg":"str type expected","type":"type_error.str"}]} status_code: 422, type: unhandled_error_type, code: unhandled_error, link:
Traceback:

File "~/.../.pyenv/versions/3.11.2/envs/dev/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "~/.../clip/lib/pages/multi_modal_search.py", line 155, in <module>
    main()
File "~/.../clip/lib/pages/multi_modal_search.py", line 94, in main
    image_results = client.index("my-first-index").search(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.../.pyenv/versions/3.11.2/envs/dev/lib/python3.11/site-packages/marqo/index.py", line 169, in search
    res = self.http.post(
          ^^^^^^^^^^^^^^^
File "~/.../.pyenv/versions/3.11.2/envs/dev/lib/python3.11/site-packages/marqo/_httprequests.py", line 96, in post
    return self.send_request(s.post, path, body, content_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.../.pyenv/versions/3.11.2/envs/dev/lib/python3.11/site-packages/marqo/_httprequests.py", line 74, in send_request
    return self.__validate(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
File "~/.../.pyenv/versions/3.11.2/envs/dev/lib/python3.11/site-packages/marqo/_httprequests.py", line 131, in __validate
    convert_to_marqo_error_and_raise(response=request, err=err)
File "~/.../.pyenv/versions/3.11.2/envs/dev/lib/python3.11/site-packages/marqo/_httprequests.py", line 145, in convert_to_marqo_error_and_raise
    raise MarqoWebError(message=response_msg, code=code, error_type=error_type,
```

**Expected behavior**
A response with similar documents

**Comment by pandu-k** [comment]
Hi @ILidzhade ! What Marqo version are you using? You can find this with the `get_marqo()` endpoint:

```
mq.get_marqo()
```

**Comment by ILidzhade** [comment]
HI @pandu-k, this is what I got
`{'message': 'Welcome to Marqo', 'version': '0.0.12'}`

**Comment by jn2clark** [comment]
@ILidzhade That feature was released in 0.0.13. If you upgrade your marqo version to the latest it will work. Note: if you are using the default configuration (a single docker container) then you might also want to transfer existing data. If that is the case, follow the instructions here https://marqo.pages.dev/0.0.16/Advanced-Usage/transferring_state/. If you do not need to transfer any data then just upgrade to the latest per the getting started guide https://marqo.pages.dev/0.0.16/

**Comment by ILidzhade** [comment]
@jn2clark I ran this command to import the package but it looks like I am already on the latest pip version. 
`pip install --upgrade marqo`. So I'm not sure how to upgrade

running `pip show marqo` I get:
```
Name: marqo
Version: 0.8.0
Summary: Tensor search for humans
Home-page: 
Author: marqo org
Author-email: org@marqo.io
License: 
Location: ~/.../.pyenv/versions/dev/lib/python3.11/site-packages
Requires: pydantic, requests, urllib3
Required-by: 
```

**Comment by jn2clark** [comment]
Apologies, I should have clarified. You upgraded the client which is the right thing to do but you will also need to upgrade the marqo service running in docker. 
```
docker pull marqoai/marqo:latest
docker run --name marqo -it --privileged -p 8882:8882 --add-host host.docker.internal:host-gateway marqoai/marqo:latest
```
If you already have marqo then you will need to remove it or change the name `--name` in the above command to something else. 

On a side note, If you are not doing it already you can run marqo and marqo-os separately. This will allow easier upgrading of marqo as no transfer of state needs to occur. The following commands are how you can run marqo and marqo-os seperately (instead of a single marqo container running both). See here https://github.com/marqo-ai/marqo/tree/mainline/src/marqo or below:

```
# run marqo-os which has the storage
docker run --name marqo-os -id -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" marqoai/marqo-os:0.0.3
# run marqo and point it to marqo-os
docker run --name marqo --privileged -p 8882:8882 --add-host host.docker.internal:host-gateway \
         -e "OPENSEARCH_URL=https://localhost:9200" marqo_docker_0
```

**Comment by ILidzhade** [comment]
Thank you @jn2clark for your help. I was able to upgrade to
`{'message': 'Welcome to Marqo', 'version': '0.0.16'}`

but I don't think it resolved the issue, because I still get this error:
```
MarqoWebError: MarqoWebError: MarqoWebError Error message: {"detail":[{"loc":["body","q"],"msg":"str type expected","type":"type_error.str"},{"loc":["body","q"],"msg":"value is not a valid dict","type":"type_error.dict"}]} status_code: 422, type: unhandled_error_type, code: unhandled_error, link:
```

And I think something broke with the upgrade as I'm now having issues using the gpu. I get this error:
```
MarqoWebError: MarqoWebError: MarqoWebError Error message: {'message': 'Requested device is not available to this Marqo instance. Requested device: `cuda`', 'code': 'hardware_compatability_error', 'type': 'invalid_request', 'link': None} status_code: 400, type: invalid_request, code: hardware_compatability_error, link:
```

**Comment by pandu-k** [comment]
Hi @ILidzhade . If you have a GPU device, you need to add the `--gpus all` flag to run Marqo like this:
```
docker run --name marqo --gpus all --privileged -p 8882:8882 --add-host host.docker.internal:host-gateway marqoai/marqo:latest
```
See [here](https://docs.marqo.ai/0.0.16/using_marqo_with_a_gpu/) for full GPU documentation. 
The same advice applies regarding `--name`: "if you already have marqo then you will need to remove it or change the name `--name` in the above command to something else."

Finally, can you confirm you are searching the same instance. Can you run this script and paste the output to this thread? 

```
import pprint
import marqo
from marqo import errors


mq = marqo.Client()
print("Marqo version information:\n", mq.get_marqo())
print("Marqo python client information:\n", marqo.supported_marqo_version())
index_name = "test_index"

try:
    mq.index(index_name).delete()
except errors.MarqoWebError:
    pass

mq.create_index(index_name=index_name)

add_docs_res = mq.index(index_name).add_documents(
    documents=[{"Title": "Hippo habitats", "Description": "A short summary"}],
)
res = mq.index(index_name).search({"adventure": 1, "time": -1},  searchable_attributes=['Title'])
print("search results")
pprint.pprint(res)
```

**Comment by ILidzhade** [comment]
this is the output I received:
```
Marqo version information:
 {'message': 'Welcome to Marqo', 'version': '0.0.16'}
Marqo python client information:
 This Marqo python client is built for Marqo release (0.0.16) 
https://github.com/marqo-ai/marqo/releases/tag/0.0.16
search results
{'hits': [{'Description': 'A short summary',
           'Title': 'Hippo habitats',
           '_highlights': {'Title': 'Hippo habitats'},
           '_id': 'e73912ca-f692-4a09-a42c-f252298fb822',
           '_score': 0.5615684}],
 'limit': 10,
 'offset': 0,
 'processingTimeMs': 54,
 'query': {'adventure': 1.0, 'time': -1.0}}
```

It still doesn't work if I try to use `CUDA`
`res = mq.index(index_name).search({"adventure": 1, "time": -1},  searchable_attributes=['Title'], device="cuda")`

In the docs it's mentioned that Marqo defualts to: 'CUDA 11.4.2'
I'm running `CUDA 11.5`. Could that be the issue? How do I specify a different version for Marqo to use?

**Comment by jn2clark** [comment]
hi @ILidzhade , 
1) can you run the following from the python client to confirm the GPU is being detected?
```
results = mq.get_cuda_info()
```
2) can you also confirm that the `--gpus all` flag was in the docker run command? The flag cannot appear at the end (see  @pandu-k 's previous comment)
3) was the GPU working before upgrading Marqo? As long as the driver supports the CUDA version it should work.
4) can you paste the error message you get from the following?
```
res = mq.index(index_name).search({"adventure": 1, "time": -1},  searchable_attributes=['Title'], device="cuda")
```

**Comment by ILidzhade** [comment]
Hi @jn2clark and @pandu-k It's all working now, thank you so much for your help. I think I must have missed a step setting up the new docker container. I was able to run through the instructions here again, and I just had to recreate the index, but it looks like it's working fine now

**Comment by pandu-k** [comment]
Great to hear that it's working for you now @ILidzhade ! Let us know if you have any feature requests/bugs to report after getting started.
