### ISSUE TITLE
[BUG] Undesired/Random Results

### ISSUE THREAD

**Issue by anlrde** [marqo-ai/marqo#415]
**Describe the bug**
Hi there! Saw the demos of Marqo and it looks really interesting and promising!
I went ahead and followed the [Getting Started Guide](https://docs.marqo.ai/0.0.16/) to install and setup Marqo with Docker on my machine.
It all worked fine and I could complete the tutorial with the `spacesuit` demo!
However, once I started creating my own index and filling it with some test image data (which all worked without errors), my search queries would return incorrect/random results.
For example with the following data:

1. Creating Image Index
```
curl -s -XPOST -H 'Content-type: application/json' http://localhost:8882/indexes/image-index -d '{"index_defaults": { "treat_urls_and_pointers_as_images": True, "model": "ViT-L/14" }}'
```

Returns:
```
{
  "acknowledged": true,
  "shards_acknowledged": true,
  "index": "image-index"
}
```
2. Filling the index with three example images
```
curl -s -XPOST -H 'Content-type: application/json' http://localhost:8882/indexes/image-index/documents -d '[{
  "context": "test img 1",
  "img": "https://source.unsplash.com/qO-PIF84Vxg"
},
{
  "context": "test img 2",
  "img": "https://source.unsplash.com/p6yH8VmGqxo"
},
{
  "context": "test img 3",
  "img": "https://source.unsplash.com/uran4t5LlvI"
}]'
```
(The first image is a dog, the second a cat, and the third a mountain)

Returns:
```
{
  "errors": false,
  "processingTimeMs": 1677.2972509970714,
  "index_name": "image-index",
  "items": [
    {
      "_id": "31d9d82a-ffc1-4129-b6b9-3850724a4f1e",
      "result": "created",
      "status": 201
    },
    {
      "_id": "b5bcd62b-c471-4476-a887-42e7df965485",
      "result": "created",
      "status": 201
    },
    {
      "_id": "a9331215-59c8-4fb8-8bcf-a18837717d48",
      "result": "created",
      "status": 201
    }
  ]
}
```
3. Searching for a specific thing
```
curl -s -XPOST -H 'Content-type: application/json' http://localhost:8883/indexes/image-index/search -d '{ "q": "a mountain" }'
```

Returns:
```
{
  "hits": [
    {
      "img": "https://source.unsplash.com/qO-PIF84Vxg",
      "context": "test img 1",
      "_id": "31d9d82a-ffc1-4129-b6b9-3850724a4f1e",
      "_highlights": {
        "context": "test img 1"
      },
      "_score": 0.87007356
    },
    {
      "img": "https://source.unsplash.com/p6yH8VmGqxo",
      "context": "test img 2",
      "_id": "b5bcd62b-c471-4476-a887-42e7df965485",
      "_highlights": {
        "context": "test img 2"
      },
      "_score": 0.86996776
    },
    {
      "img": "https://source.unsplash.com/uran4t5LlvI",
      "context": "test img 3",
      "_id": "a9331215-59c8-4fb8-8bcf-a18837717d48",
      "_highlights": {
        "context": "test img 3"
      },
      "_score": 0.86870563
    }
  ],
  "query": "a mountain",
  "limit": 10,
  "offset": 0,
  "processingTimeMs": 52
}
```

-> Result is the same order as input data, first two results are completely incorrect

What am I doing wrong?
I'd be grateful for any kind of help!

**Comment by jn2clark** [comment]
Hi @anlrde ! Try and restrict the search to the `img` field by using the [searchableAttributes](https://marqo.pages.dev/0.0.16/API-Reference/search/) when calling search. this will restrict the search to the images only

**Comment by anlrde** [comment]
Omg, I can't believe that it was that simple! It seems to work with setting `searchableAttributes": [ "img" ]`!
Thank you so much for your super-quick help, @jn2clark! Appreciate it!

I will try to test Marqo a bit more now that it's working with the image index! Thank you so much!!

I'm currently also playing around with a text-only index, and I do have a question regarding text documents:
When inputting text data, what is the recommended amount of data to put in one document and field?

For example, say I'm trying to index text-documents with a few thousand words each: Should I just input the data like that:
```
{
  "text": "all text goes here..."
}
```
or should I split it up in multiple fields? (if yes, how long should each part be?) - like that:
```
{
  "text_parts":  [
    "first text part",
    "second text part",
    "..."
  ]
}
```
or should I split the text up in different parts and index them as separate documents, like that:
```
document 1:
{
  "text": "first text part"
}
document: 2:
{
  "text": "second text part"
}
```

Is there a recommended way which is best for search quality and performance?
I couldn't find an answer to this question in the docs.
Thanks a lot!

**Comment by jn2clark** [comment]
I think that latter is the best way to start as it tends to be easier to iterate structure wise.
```
document 1:
{
  "text": "first text part"
}
document: 2:
{
  "text": "second text part"
}
```
Marqo has internal chunking for text which is set at index time https://marqo.pages.dev/0.0.16/Preprocessing/Text/
So as long as the text in the documents is longer than a few sentences you should be good. the exact setup depends on the use case but one to several paragrpahs per document is a good place to start

**Comment by jn2clark** [comment]
Going to close this issue. Feel free to create a new one if something else comes up or you can join the [slack community](https://join.slack.com/t/marqo-community/shared_invite/zt-1d737l76e-u~b3Rvey2IN2nGM4wyr44w) and ask for help there.
