### ISSUE TITLE
Docker not installing 

### ISSUE THREAD

**Issue by Abubakarsq** [marqo-ai/marqo#45]
I am having trouble installing Docker on my machine, it tells me that I need windows 10 pro or later.

![image](https://user-images.githubusercontent.com/89004030/188499447-19cae387-9175-49fc-92d9-9122cc5c0a5a.jpeg)

**Comment by jn2clark** [comment]
Thanks @Abubakarsq . You will have to refer to the Docker installation instructions and requirements for installing on Windows (https://docs.docker.com/desktop/install/windows-install/).
