### ISSUE TITLE
[BUG] OOM during indexing 

### ISSUE THREAD

**Issue by patelprateek** [marqo-ai/marqo#451]
OOM memory when indexing and similar for some search request
I am trying to understand is this due to GPU , do we do hnsw indexing and search using GPU ?

**Comment by pandu-k** [comment]
Do you mind adding more details? For example, the number of documents you are trying to index, there number of search requests, and the machine's available disk, RAM and GPU/CPU? 

As far as I know, HNSW traversal uses the CPU

**Comment by patelprateek** [comment]
oh ok  if hnsw indexing and search is all on cpu we can close this because then it is probably some issue with my model inference on gpu
