### ISSUE TITLE
[BUG] filters dont work on lexical searches

### ISSUE THREAD

**Issue by jess-lord** [marqo-ai/marqo#458]
**Describe the bug**

**To Reproduce**
1. run this query on documents that have both a content field and a filename field. 
{
  "q": "RequiredString123",
  "searchMethod": "LEXICAL",
  "searchableAttributes": [
    "content"
  ],
  "limit": 10,
  "showHighlights": true,
  "filter": "filename:Important_File.pdf"
}

**Expected behavior**
Only the requested filename should appear in the results

**Additional context**
TENSOR filters work, but not LEXICAL.

**Comment by wanliAlex** [comment]
Hi, thanks for submitting the bug. We are working on this and will let you know as soon as possible.

**Comment by pandu-k** [comment]
The problem probably stems from an error in parsing the `.` in the string to be filtered.

**Comment by wanliAlex** [comment]
Hello @jess-lord 

Thank you for bringing this issue to our attention. We have identified that the difference in the tokenization of filter strings between lexical search and tensor search is causing the bugs that you have encountered. 

We have plans to make the tokenization consistent in the future map, but for now, we suggest using the following solution to ensure an exact match in lexical search by adding `"\` before and after the filter content:
```json
{
  "q": "RequiredString123",
  "searchMethod": "LEXICAL",
  "searchableAttributes": [
    "content"
  ],
  "limit": 10,
  "showHighlights": true,
  "filter": "filename: \"Important_File.pdf\""
}
```

Please note that no change is necessary for tensor search.

We hope that this solution helps you. If you have any further questions or concerns, please don't hesitate to let us know.

**Comment by jess-lord** [comment]
fantastic - thanks @pandu-k and @wanliAlex!
