### ISSUE TITLE
Incorrect default argument in "search" function

### ISSUE THREAD

**Issue by aryanagarwal9** [marqo-ai/marqo#49]
**Describe the bug**

**To Reproduce**
call the search method and don't specify the "search_method"

**Expected behavior**
Should have displayed the search results

**Screenshots**
`marqo.errors.MarqoWebError: MarqoWebError: MarqoWebError Error message: {"detail":[{"loc":["body","searchMethod"],"msg":"NEURAL is not a valid SearchMethod","type":"value_error"}]}
status_code: 422, type: unhandled_error_type, code: unhandled_error, link:
`

**Desktop (please complete the following information):**
MacOS Montery v12.5

**Additional context**

**Comment by pandu-k** [comment]
Can you please try these 2 steps:
1. to reinstall py-marqo: `pip install --force-reinstall marqo `
2. run the latest marqo docker image

**Comment by aryanagarwal9** [comment]
Using the latest version works:
`pip install marqo --upgrade`
