### ISSUE TITLE
How are query vectors combined for search?

### ISSUE THREAD

**Issue by junwang-wish** [marqo-ai/marqo#505]
Awesome work! 

I know `marqo` supports searching with `{"shirts": 1.0, "blue": 1.0, "https://cyberpunk_image.png": 1.0}` which is awesome, but underneath, does it do a simple linear combination of the vectors like
```
actual_search_vector = clip_text("shirts") * 1.0 + clip_text("blue") * 1.0 + clip_image("https://cyberpunk_image.png") * 1.0
retrieved_items = ann_search(actual_search_vector, distance="cosine", algo="hnsw")
```
Knowing how this is done gives more guarantee that it fits my use case

**Comment by jn2clark** [comment]
hi @junwang-wish , you are correct. There are other options for combing as well which we will explore in the future.

**Comment by junwang-wish** [comment]
Thanks!
