### ISSUE TITLE
[ENHANCEMENT] change the web background color of  doc please

### ISSUE THREAD

**Issue by msskaa12** [marqo-ai/marqo#599]
the darkblue color  （dark-blue-color: #0c0f37;）is a bad choice as  reading  background。

Blue light tends to scatter easily because its wavelength is short, so that our eyes have to work harder to focus on reading. If we use our eyes for a long time without relaxing them, it will lead to fatigue.

By the way ，the vi color pattern is nice.

**Comment by OwenElliottDev** [comment]
Hi @msskaa12, we have recently done a complete overhaul on the style for the documentation that should address your concerns.

https://docs.marqo.ai/1.4.0/
