### ISSUE TITLE
[Question] Mulitmodal Index

### ISSUE THREAD

**Issue by ajaybabu20** [marqo-ai/marqo#613]
Is it possible to add multiple images to a document?
For example 
`
{'att1': 'This is a cookie?',
 'images': [
'https://image1' , 'https://image2', 'https://image3'
]}
`

**Comment by pandu-k** [comment]
Hi Ajay! You would use multimodal fields for this purpose, please see documentation [here](https://docs.marqo.ai/1.3.0/Advanced-Usage/document_fields/#multimodal-combination-object) with a key for each image URL. We don't support a list of images yet unfortunately
