### ISSUE TITLE
[BUG] Performing a lexical search on a structured index always results in a _score of 0.0

### ISSUE THREAD

**Issue by Art480-arch** [marqo-ai/marqo#855]
**Describe the bug**
When I perform a lexical search on a structured index, the results are returned as expected, but the _score attribute is 0.0.
A tensor search always returns a non-zero _score on both structured and unstructured indexes, but a lexical search only returns a _score on an unstructured index.

**To Reproduce**
1. Follow the first 2 steps of the README to start a docker container and install marqo
2. Follow this [Cockbook ](https://docs.marqo.ai/2.7/Cookbook/indexes/creating_an_unstructured_index/text_index/)to create a strcutured index:
3. Perform the search
4. The result looks like this: 
{'hits': [{'_id': '1', 'text_field': 'New York', '_score': 0.0, '_highlights': []}], 'query': 'New York', 'limit': 10, 'offset': 0, 'processingTimeMs': 57}

**Expected behavior**
I expect a non-zero _score, like when an unstructured index is used.

**Desktop:**
 - OS: Windows 11
 - Marqo Version: 2.7.2
 - Python Version: 3.12.3

**Comment by farshidz** [comment]
Hi @Art480-arch . Thanks a lot for reporting this. This issue will be addressed in Marqo 2.9 which will be released tomorrow.

**Comment by Art480-arch** [comment]
Fixed in Version 2.9.0
