### ISSUE TITLE
first search is always 5 seconds longer then following

### ISSUE THREAD

**Issue by danyilq** [marqo-ai/marqo#9]
Im not sure if it is fixable or not but processingTimeMs of the first search after initialisation of client is always 5.2+ seconds, while all the following no matter if I'm trying same index or any other are around 100ms

**Comment by jn2clark** [comment]
We now pre-warm some models on startup via a startup script https://github.com/marqo-ai/marqo/blob/mainline/src/marqo/tensor_search/on_start_script.py#L77-L84. Setting this via configuration is something for the future.
