### ISSUE TITLE
[BUG] `PIL.UnidentifiedImageError: cannot identify image file` during `index.add_documents(...)`

### ISSUE THREAD

**Issue by ash0ts** [marqo-ai/marqo#90]
**Describe the bug**
When adding image files from a URL I received the above error. To mitigate the issue which I believe could've occurred due to rate-limiting on my end, I pre-downloaded all images and served it similar to the [apparel demo](https://marqo.pages.dev/End-to-End%20Examples/streamlit_demo/) i.e. via `python3 -m http.server 8222`. This also still fails with the above error. As a workaround, I am manually inserting each document one at a time as shown below

```
for data_doc in tqdm(data):
    try:
        responses = mq.index(index_name).add_documents([data_doc], device=device)
        # print(f"<SUCCESS>\nAdded prompt:\n{data_doc['prompt']}\nURI: {data_doc['raw_discord_data_image_uri']}\n")
    except:
        print(f"<FAILURE>\nSkipping prompt:\n{data_doc['prompt']}\nURI: {data_doc['raw_discord_data_image_uri']}\n")
```
Doing it one at a time does not fail for the direct URL or the pre-downloaded one. I will be continuing my current flow by pre-downloading still. For testing the above is fine but for my real workload of 10M data points this is a blocker.

**To Reproduce**
```
marqo_settings = {
    "index_defaults": {
        "treat_urls_and_pointers_as_images": True,
        # "image_preprocessing": {
        #     "patch_method": "frcnn"
        # },
        "model":"ViT-B/16",
        "normalize_embeddings":True,
    },
}
```
Using settings where I include a model for dense retrieval and a URI which may look like this url: https://cdn.discordapp.com/attachments/1005627160410722305/1006718276879003738/rick_and_morty_as_the_thing_fused_with_lovecraft_high_details_intricate_details_renaissance_style_painting_by_vincent_di_fate_artgerm_julie_bel_-H_768_-n_9_-i_-S_687487568_ts-1660090738_idx-3.png
or this internal path: http://host.docker.internal:8222/./artifacts/sample_prompts:v1/sample_prompts/rick_and_morty_as_the_thing_fused_with_lovecraft_high_details_intricate_details_renaissance_style_painting_by_vincent_di_fate_artgerm_julie_bel_-H_768_-n_9_-i_-S_687487568_ts-1660090738_idx-3.png
I get the above behavior consistently.

This behavior comes from `/app/src/marqo/s2_inference/clip_utils.py` which errs at `Image.open(requests.get(image, stream=True).raw)`

**Expected behavior**
Instead of erring the whole insert, I would like an option to ignore errors and be told via logs, stdout, and a response that problematic data points were not inserted at the very least.

**Desktop (please complete the following information):**
Using Google's Vertex Workbench
- OS: Debian 10
- Environment: Python 3 configured for CUDA 11.0 and Intel MKL
- Machine Type: n1-standard-4 (4 vCPUs, 15GB RAM)

**Comment by ash0ts** [comment]
So as a follow-up, **_there was a mistake on my part_**. I had a field that contained NaN's which was causing separate issues internally within margo upon investigations of the responses returned by marqo (unfortunately I did not copy the response to paste here before clearing the output) which was a JSON encoding error for the NaN values. Upon removing of any problematic fields, the insertion of the pre-downloaded files worked as intended and without issue. It is strange that this original error is either inconsistent or raised under unusual circumstances (not the expected issue as mentioned above).

These same problematic fields were present in my data that was not pre-downloaded but as I am not doing that flow anymore I have not tested if removal fixes this issue for that. I can test if you would like!

**Comment by jn2clark** [comment]
Thanks @ash0ts for posting this. We are looking at the error handling of individual documents so they don't disrupt the entire batch (and also will be more informative). We'll update here when its done.

**Comment by jn2clark** [comment]
PR is under way here https://github.com/marqo-ai/marqo/pull/97

**Comment by jn2clark** [comment]
PR merged https://github.com/marqo-ai/marqo/pull/97. I will update when it makes it to docker hub version. Otherwise you could re-build docker now to use it.

**Comment by jn2clark** [comment]
This has now made its way into docker as well (0.0.3).
