### ISSUE TITLE
[ENHANCEMENT] Run Marqo on Google colab

### ISSUE THREAD

**Issue by jn2clark** [marqo-ai/marqo#95]
**Is your feature request related to a problem? Please describe.**
A demonstration of Marqo running on google colab

**Describe the solution you'd like**
Marqo running in colab

**Additional context**
A good start might be to reproduce the readme examples in google colab

**Comment by mory91** [comment]
Hi,
I would be happy to work on this.

**Comment by jn2clark** [comment]
Fantastic @mory91 ! Let us know if you run into any issues.

**Comment by mory91** [comment]
Hi,
Since Colab is not able to run docker, what do you suggest for the server? Is it okay to use a test cloud instance of marqo? Can I have the credentials for one? Or you suggest another way?
