### ISSUE TITLE
[BUG] stuck at "Waiting for vector store to be available..."

### ISSUE THREAD

**Issue by Art480-arch** [marqo-ai/marqo#980]
**Describe the bug**
When starting a marqo container on a Linux server, it gets stuck at "Waiting for vector store to be available...".

**To Reproduce**
docker run --name marqo -it -p 8882:8882 marqoai/marqo:2.12.0
![marqo_waiting_for_vector_store](https://github.com/user-attachments/assets/11f4e1a8-ac32-4536-942d-068afeaaff23)

**Troubleshooting**
- I let it loop for ~2h to make sure it wasn't just slow
- I tried version 2.9.0, 2.11.0 and 2.12.0 (all work fine on my local machine, but not on the server)
- I checked the Docker installation. Other containers and the [hello-world](https://hub.docker.com/_/hello-world) image work fine
- I have checked the cpu flags
- I have tried starting the container from Plesk instead of the console
- Checked available memory
- Tried different ports in to rule out a collision
- Restarted the container several times, removing the image and container between attempts.
- I got past "Waiting for vector store to be available..." once and ended up with this error: [kazoo_error_marqo.txt](https://github.com/user-attachments/files/17098439/kazoo_error_marqo.txt)

**Environment:**
- OS: Ubuntu 20.04.6 LTS
- Kernel: 5.4.0
- Architecture: x86_64
- Total RAM: 32GB
- Marqo version 2.9.0, 2.11.0 and 2.12.0
- Docker version 27.0.3

**Additional context**
I'm happy to provide any additional information you may require.

**Comment by papa99do** [comment]
Hello @Art480-arch , thanks for reporting this bug. Could you please try to check the vespa log when the container is running by using following commands?
```
docker exec -it marqo bash
less /opt/vespa/logs/vespa/vespa.log
```

Also, could you please check if your docker machine's disk and memroy usage is below 75% when starting marqo? If Vespa detects that the usage is higher than this, it will not start. Please let us know if this solves your issue. Thanks.

**Comment by Art480-arch** [comment]
Apologies for the late reply. The Vespa log sent me down a rabbit hole.
Disk and memory usage are 5-10% during the "Waiting for vector store" loop.

But the vespa log shows multiple warnings:
[**warning**][os,thread] Failed to start the native thread for java.lang.Thread "feedapi-handler-1-thread-17"
[**warning**][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 512k, guardsize: 0k, detached.
[**warning**][os,thread] Failed to start the native thread for java.lang.Thread "component-deconstructor-1-thread-1"
[**warning**][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 512k, guardsize: 0k, detached.
[**warning**][os,thread] Failed to start the native thread for java.lang.Thread "Thread-2"

And most importantly:
[warning][pagesize] **_UseTransparentHugePages_** disabled, transparent huge pages are not supported by the operating system.

I'm still working on making THP available. Would it be possible to run marqo without THP? The Vespa website says THP offers improved performance but doesn't say if it's required.

**Comment by Art480-arch** [comment]
I can't say for certain that Transparent Huge Pages (THP) was the root cause, as there were many changes during the server migration. However, the issue seems to be resolved now.

If anyone encounters a similar problem in the future, I strongly recommend checking the Vespa log.
