### ISSUE TITLE
[BUG] Can't use any tools with marqo

### ISSUE THREAD

**Issue by akhovanska** [marqo-ai/marqo#99]
After installing marqo and marqo libraries, I can't run any code using marqo. Even simple codes from readme 

Error:
ConnectionRefusedError: [Errno 61] Connection refused
HTTPConnection object at 0x7f7860bce220>: Failed to establish a new connection: [Errno 61] Connection refused
in send_request
    raise BackendCommunicationError(str(err)

Desktop
 - OS (macOS 12.0.1)

**Comment by pandu-k** [comment]
Are you using an arm64 mac (Apple Silicon, M1 or M2 chip)? 

If so please refer to these instructions in the README to set up Marqo: 

https://github.com/marqo-ai/marqo#m-series-mac-users

**Comment by akhovanska** [comment]
no, it's usual MacBook Air 13" 2020

**Comment by jn2clark** [comment]
hi @akhovanska , are you able to run the following commands to start marqo using docker?
```
docker pull marqoai/marqo:0.0.3;
docker run --name marqo -it --privileged -p 8882:8882 --add-host host.docker.internal:host-gateway marqoai/marqo:0.0.3
```

**Comment by akhovanska** [comment]
docker: Error response from daemon: Conflict. The container name "/marqo" is already in use by container "eff89c58737dcee665346767032ffb776c69033e129099ef675e19e9b47e861a". You have to remove (or rename) that container to be able to reuse that name.

seems it's in use, but still no code is working

**Comment by jn2clark** [comment]
thanks! try the following commands (also found here https://marqo.pages.dev/starting_and_stopping/):
```
docker stop marqo
docker start marqo
docker attach marqo
```

**Comment by akhovanska** [comment]
that's the result 

Is the docker daemon running?
Process dockerd is not running yet.
dockerd is not running after max time

**Comment by jn2clark** [comment]
Thanks. Would you be able to paste the full output? Alternatively, if you have nothing you want to keep from before you can try the following (note, this will remove any data stored in Marqo);

```
docker stop marqo
docker rm -f marqo
docker pull marqoai/marqo:0.0.3;
docker run --name marqo -it --privileged -p 8882:8882 --add-host host.docker.internal:host-gateway marqoai/marqo:0.0.3
```
If you do need to keep any already indexed data we can try something else.

**Comment by akhovanska** [comment]
<img width="920" alt="Screenshot 2022-09-30 at 14 37 57" src="https://user-images.githubusercontent.com/98605728/193262487-1fd1ef84-0939-4997-b42c-9baedecb9852.png">

**Comment by akhovanska** [comment]
seems it was the solution. @jn2clark thank you!

**Comment by jn2clark** [comment]
Great! I will close the issue.
